### ISSUE TITLE
Spam dropdown create an error

### ISSUE THREAD

**Issue by Tweentyy** [AbdullahChauhan/custom-dropdown#96]
Hello,
If we spam the open/close dropdown with the example in the doc, an error is produced : 

```dart
'package:flutter/src/widgets/overlay.dart': Failed assertion: line 1823 pos 12: 'SchedulerBinding.instance.schedulerPhase != SchedulerPhase.persistentCallbacks': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      _OverlayPortalState.hide (package:flutter/src/widgets/overlay.dart:1823:12)
#3      OverlayPortalController.hide (package:flutter/src/widgets/overlay.dart:1571:13)
#4      _OverlayBuilderState.hideOverlay (package:animated_custom_dropdown/widgets/overlay_builder.dart:40:23)
#5      _AnimatedSectionState.prepareAnimations.<anonymous closure> (package:animated_custom_dropdown/widgets/animated_section.dart:39:36)
#6      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:240:19)
#7      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:897:7)
#8      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:690:7)
#9      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:541:12)
#10     _AnimatedSectionState.runExpand (package:animated_custom_dropdown/widgets/animated_section.dart:53:22)
#11     _AnimatedSectionState.didUpdateWidget (package:animated_custom_dropdown/widgets/animated_section.dart:60:5)
#12     StatefulElement.update (package:flutter/src/widgets/framework.dart:5789:55)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#16     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#21     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#27     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#32     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#34     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#39     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#49     StatelessElement.update (package:flutter/src/widgets/framework.dart:5693:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#55     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#57     Element.updateChildren (package:flutter/src/widgets/framework.dart:4090:32)
#58     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7060:17)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#60     Element.updateChildren (package:flutter/src/widgets/framework.dart:4090:32)
#61     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7060:17)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#64     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#66     BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693:15)
#67     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#68     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
#69     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162:21)
#70     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#71     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#72     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#73     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#74     _invoke (dart:ui/hooks.dart:312:13)
#75     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#76     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
The AnimationController notifying status listeners was: AnimationController#01ac7(⏮ 0.000; paused)
```

Thanks :D

**Comment by iamalok12** [comment]
+1

**Comment by AbdullahChauhan** [comment]
Hey @Tweentyy @iamalok12 
Kindly tell me your Flutter And Package version?

**Comment by iamalok12** [comment]
@AbdullahChauhan  I am using Flutter 3.24.3 and package 3.1.1

**Comment by AbdullahChauhan** [comment]
@iamalok12 Thanks. I'll check ...
